include $(THEOS)/makefiles/common.mk

BUNDLE_NAME = LockscreenBrightnessSlider16Prefs
LockscreenBrightnessSlider16Prefs_FILES = LSBSRootListController.m
LockscreenBrightnessSlider16Prefs_FRAMEWORKS = UIKit Foundation CoreFoundation
LockscreenBrightnessSlider16Prefs_PRIVATE_FRAMEWORKS = Preferences
LockscreenBrightnessSlider16Prefs_CFLAGS = -fobjc-arc -Wall -Wextra -Wno-unused-parameter
LockscreenBrightnessSlider16Prefs_INSTALL_PATH = /Library/PreferenceBundles
LockscreenBrightnessSlider16Prefs_RESOURCE_DIRS = Resources

include $(THEOS_MAKE_PATH)/bundle.mk
