#!/bin/sh
set -e

# Ask the package manager to restart SpringBoard after installation.
if [ "$1" = configure ]; then
    if [ -n "$CYDIA" ]; then
        eval "echo 'finish:restart' >&${CYDIA%% *}"
    fi
fi

exit 0
